############################################################
# Launcher for Galaxy container
# This is a template, the following values must be replaced:
#   - $${INSTANCE_NAME}, name for the instance
#   - $${INSTANCE_PORT_1}, port number for Galaxy instance
#   - $${ADMIN_ACCOUNTS}, list of admin email accounts for Galaxy and Galaksio (emails separated by comma)
#   - $${GALAXY_INSTANCE_TITLE}, custom title for the Galaxy server (shown in home page)
############################################################

version: '2'
services:

    $${INSTANCE_NAME}-galaxy:
      image: bgruening/galaxy-stable
      container_name: $${INSTANCE_NAME}-galaxy
      environment:
        - NONUSE=reports
        - GALAXY_CONFIG_ADMIN_USERS=$${ADMIN_ACCOUNTS}
        - GALAXY_CONFIG_BRAND="$${GALAXY_INSTANCE_TITLE}"
        - GALAXY_CONFIG_TOOL_CONFIG_FILE=config/tool_conf.xml.sample,config/shed_tool_conf.xml.sample,/local_tools/custom_tools.xml
      depends_on:
        - $${INSTANCE_NAME}-galaxy-data
      volumes_from:
        - $${INSTANCE_NAME}-galaxy-data
      ports:
        - "$${INSTANCE_PORT_1}:80"

    $${INSTANCE_NAME}-galaxy-data:
      image: busybox
      container_name: $${INSTANCE_NAME}-galaxy-data
      volumes:
        - /data/$${INSTANCE_NAME}-data/galaxy-data:/export
        - /data/$${INSTANCE_NAME}-data/galaxy-custom-tools/:/local_tools
